# Generated by Django 3.1.3 on 2022-02-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.CharField(max_length=4, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='created_date',
            field=models.DateField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='explanation',
            field=models.TextField(verbose_name='Explanation'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='genius',
            field=models.CharField(max_length=20, verbose_name='Genius'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='type',
            field=models.CharField(max_length=20, verbose_name='Type'),
        ),
    ]
