# Generated by Django 3.1.3 on 2022-02-12 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_meeting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meeting',
        ),
    ]
