# Generated by Django 3.1.3 on 2022-02-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0006_delete_attend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.CharField(choices=[('attended', 'attended'), ('notattended', 'notattended')], max_length=13, null=True)),
            ],
        ),
    ]
