# Generated by Django 3.1.3 on 2022-02-13 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0007_attend'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attend',
        ),
    ]
