# Generated by Django 3.1.3 on 2022-02-12 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petowner',
            options={'verbose_name_plural': 'Additional information for the user'},
        ),
        migrations.AlterField(
            model_name='petowner',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='petowner',
            name='tel',
            field=models.CharField(max_length=13, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='petowner',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
