# Generated by Django 3.1.3 on 2022-02-12 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_meeting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meeting',
        ),
    ]
