# Generated by Django 3.1.3 on 2022-02-12 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_meeting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='created_date',
            new_name='meeting_date',
        ),
    ]
