# Generated by Django 3.1.3 on 2022-02-12 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_delete_meeting'),
        ('user', '0006_auto_20220212_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='pet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pet.pet'),
        ),
    ]
