# Generated by Django 3.1.3 on 2022-02-12 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_meeting_pet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='pet',
        ),
    ]
