# Generated by Django 3.1.3 on 2022-02-12 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_meeting_pet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='meeting',
            new_name='meeting_hour',
        ),
    ]
