# Generated by Django 3.1.3 on 2022-02-12 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0009_auto_20220212_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='petowner',
        ),
        migrations.AddField(
            model_name='meeting',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
