# Generated by Django 3.1.3 on 2022-02-12 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0013_auto_20220212_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='petowner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_petowner', to=settings.AUTH_USER_MODEL),
        ),
    ]
