# Generated by Django 3.1.3 on 2022-02-12 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_delete_meeting'),
        ('user', '0015_remove_meeting_petowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pet_name', to='pet.pet'),
        ),
    ]
