# Generated by Django 3.1.3 on 2022-02-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20220212_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_hour',
            field=models.CharField(choices=[('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], max_length=4, null=True),
        ),
    ]
