# Generated by Django 3.1.3 on 2022-02-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20220212_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attentd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.CharField(choices=[('attended', 'attended'), ('notattended', 'notattended')], max_length=13, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['meeting_date', 'meeting_hour'], 'verbose_name_plural': 'Meeting Time'},
        ),
    ]
