# Generated by Django 3.1.3 on 2022-02-13 18:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0020_attentd_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attentd',
            new_name='Attend',
        ),
    ]
