# Generated by Django 3.1.3 on 2022-02-13 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20220213_2129'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attend',
        ),
    ]
