# Generated by Django 3.1.3 on 2022-02-13 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_attend'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attend',
        ),
    ]
