# Generated by Django 3.1.3 on 2022-02-13 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_attend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attend',
            name='meeting',
        ),
    ]
