# Generated by Django 3.1.3 on 2022-02-13 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_remove_attend_meeting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attend',
        ),
    ]
